language: node_js
node_js:
  - "0.10"
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0
addons:
  firefox: "31.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - npm install slimerjs
  - npm install casperjs
script:
  - casperjs
  - casperjs tests/automation.js
  - casperjs --engine=slimerjs  tests/automation.js
  - cd java && make && cd ..
  - cd tests && make && cd ..
