language: node_js
node_js:
  - "0.10"
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=${PATH}:$TRAVIS_BUILD_DIR/node_modules/slimerjs/lib/slimer
addons:
  firefox: "31.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - npm install casperjs
  - npm install slimerjs
script:
  - casperjs $TRAVIS_BUILD_DIR/tests/automation.js
  - casperjs --engine=slimerjs $TRAVIS_BUILD_DIR/tests/automation.js
  - PATH=${PATH}:$TRAVIS_BUILD_DIR/node_modules/slimerjs/lib/slimer slimerjs
  - export PATH
  - cd java && make && cd ..
  - cd tests && make && cd ..
