language: node_js
node_js:
  - "0.10"
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0
addons:
  firefox: "31.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - npm install casperjs
  - npm install slimerjs
script:
  - casperjs $TRAVIS_BUILD_DIR/tests/automation.js
  - export PATH=${PATH}:/home/travis/.nvm/v0.10.29/lib/node_modules/slimerjs
  - casperjs --engine=slimerjs $TRAVIS_BUILD_DIR/tests/automation.js
  - slimerjs
  - cd java && make && cd ..
  - cd tests && make && cd ..
