language: node_js
node_js:
  - "0.10"
env:
  - DISPLAY=:99.0 PATH=${PATH}:$TRAVIS_BUILD_DIR/node_modules/slimerjs/lib/slimer
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - npm install casperjs
  - npm install slimerjs
script:
  - make test
